
export * as user from './acl/user'
export { default as role } from './acl/role'
export { default as permission } from './acl/permission'
export * as doctor  from './role/doctor'
export * as patient from './role/patient'
export * as schedule from './reg/schedule'
export * as register from './reg/register'
export * as department from './dep/dep'
export * as depbelong from './dep/depbelong'